// <auto-generated />
namespace DogeDaycare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddmoreinformationtoPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddmoreinformationtoPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201511140524055_Add more information to Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
