// <auto-generated />
namespace DogeDaycare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updateanimalmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateanimalmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201603240518339_Update animal model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
